version: '2'
services:
  dapp:
    image: ararachung/dapp
    environment:
      - constraint:node==master
    ports:
      - '5000:5000'
    # volumes:
    #   - ./app:/app
    depends_on:
      - redis
    networks:
      - my-net

  redis:
    image: redis:3.2.0
    networks:
      - my-net

networks:
 my-net:
   driver: overlay